import { figma } from "@figma/code-connect";
import { Alert } from "./alert.tsx";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  "https://www.figma.com/design/qz52VrR2zMqD57VorqiLmw/Atomic-Playfulness---Test?node-id=450%3A5624",
  {
    props: {
      feedback: figma.enum("Variant", {
        Critical: "critical",
        Caution: "caution",
        Positive: "positive",
        Neutral: "neutral",
        New: "new",
      }),
    },
    example: () => <Alert feedback={"neutral"}>Neutral message</Alert>,
  },
);
