import { figma } from "@figma/code-connect";
import { Badge } from "./badge.tsx";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/qz52VrR2zMqD57VorqiLmw/Atomic-Playfulness---Test?node-id=144%3A3779",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      strong: figma.enum("Weight", {
        Strong: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showTrailingIcon": figma.boolean('Show Trailing Icon'),
      feedback: figma.enum("Variant", {
        Positive: "positive",
        Caution: "caution",
        Neutral: "neutral",
        Critical: "critical",
        New: "new",
        AI: "ai",
      }),
    },
    example: (props) => (
      <Badge strong={props.strong} feedback={props.feedback}>
        Neutral message
      </Badge>
    ),
  },
);
