import { figma } from "@figma/code-connect";
import { Checkbox } from "./checkbox.tsx";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/qz52VrR2zMqD57VorqiLmw/Atomic-Playfulness---Test?node-id=127%3A712",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      indeterminate: figma.enum("Type", {
        Indeterminate: true,
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showLabel": figma.boolean('Show Label')
    },
    example: (props) => (
      <Checkbox indeterminate={props.indeterminate} disabled={props.disabled} />
    ),
  },
);
