import { figma } from "@figma/code-connect";
import { Icon } from "./icon.tsx";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Icon,
  "https://www.figma.com/design/qz52VrR2zMqD57VorqiLmw/Atomic-Playfulness---Test?node-id=53%3A132",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      name: figma.enum("Name", {
        "lucide/arrow-down": "WindArrowDown",
        "lucide/arrow-up": "SquareArrowUp",
        "lucide/arrow-right": "Weight",
        "lucide/mail": "Voicemail",
        "lucide/calendar": "Table",
        "lucide/arrow-down-right": "SquareArrowOutDownRight",
        "lucide/arrow-left": "Wheat",
        "lucide/arrow-down-left": "SquareArrowOutDownLeft",
        "lucide/arrow-down-up": "CalendarArrowDown",
        "lucide/arrow-up-right": "SquareArrowUpRight",
        "lucide/audio-lines": "Wine",
        "lucide/save": "Waves",
        "lucide/image": "Tag",
        "lucide/circle-alert": "TriangleAlert",
        "lucide/check": "UserCheck",
        "lucide/info": "Nfc",
        "lucide/minus": "UserMinus",
        "lucide/plus": "UserPlus",
        "lucide/download": "Upload",
        "lucide/bell": "Shell",
        "lucide/building-2": "Link2",
        "lucide/lock": "UserLock",
        "lucide/folder-open": "Rose",
        "lucide/megaphone": "Vegan",
        "lucide/video-off": "VideoOff",
        "lucide/trash-2": "Trees",
        "lucide/users": "Venus",
        "lucide/shopping-cart": "ShoppingCart",
        "lucide/circle-check": "CloudCheck",
        "lucide/chevron-up": "SquareChevronUp",
        "lucide/chevron-down": "Undo2",
        "lucide/chevron-right": "SquareChevronRight",
        "lucide/chevron-left": "SquareChevronLeft",
        "lucide/chevrons-left": "Cross",
        "lucide/chevrons-right": "ChevronsRightLeft",
        "lucide/circle-x": "X",
        "lucide/circle-help": "CircleDashed",
        "lucide/circle-ellipsis": "ShieldEllipsis",
        "lucide/circle-slash-2": "TicketSlash",
        "lucide/circle-play": "Play",
        "lucide/user-round": "UsersRound",
        "lucide/clock": "FolderClock",
        "lucide/code": "QrCode",
        "lucide/pencil": "PencilOff",
        "lucide/mic-off": "PinOff",
        "lucide/copy": "Crop",
        "lucide/mic": "Music",
        "lucide/eye": "Key",
        "lucide/send": "Sun",
        "lucide/video": "Video",
        "lucide/log-out": "Route",
        "lucide/eye-off": "PenOff",
        "lucide/search": "Watch",
        "lucide/funnel": "FunnelX",
        "lucide/file": "Smile",
        "lucide/mail-open": "Mailbox",
        "lucide/zap": "Zap",
        "lucide/menu": "Nut",
        "lucide/settings": "Sheet",
        "lucide/sparkles": "WandSparkles",
      }),
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('Size', {
      //   "24": "24",
      //   "16": "16"
      // })
    },
    example: (props) => <Icon name={props.name} />,
  },
);
