import { figma } from "@figma/code-connect";
import { IconButton } from "./icon-button.tsx";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/qz52VrR2zMqD57VorqiLmw/Atomic-Playfulness---Test?node-id=622%3A17723",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        disabled: true,
      }),
      size: figma.enum("Size", {
        Small: "small",
        "Extra Small": "extra-small",
      }),
      // No matching props could be found for these Figma properties:
      // "background": figma.enum('Background', {
      //   "Light": "light",
      //   "Dark": "dark"
      // })
    },
    example: (props) => (
      <IconButton
        icon={"ArrowRight"}
        disabled={props.disabled}
        size={props.size}
      />
    ),
  },
);
