import { figma } from "@figma/code-connect";
import { ProgressIndicator } from "./progress-indicator.tsx";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressIndicator,
  "https://www.figma.com/design/qz52VrR2zMqD57VorqiLmw/Atomic-Playfulness---Test?node-id=83%3A2346",
  {
    props: {
      count: figma.enum("Count", {
        "100": 100,
        "75": 75,
        "50": 50,
        "25": 25,
        "0": 0,
      }),
      // No matching props could be found for these Figma properties:
      // "style": figma.enum('Style', {
      //   "Linear Countdown": "linear-countdown",
      //   "Linear": "linear"
      // })
    },
    example: (props) => <ProgressIndicator value={props.count} />,
  },
);
