name: visual-test-update

on:
  workflow_dispatch:

env:
  CI: true

jobs:
  visual-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Update Visual Test Reference Screenshots
        run: npm run visual-test-update
